In [1]:
# Importing packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
# Reading the GcExport.csv from the data folder
# Skipping the first row of the export since it only says "batting" and "pitching"
# With usecols we can filter on the columns we need

gc_stats = pd.read_csv('data/GcExport.csv', skiprows=1, usecols=['Number', 'First', 'Last', 'GP', "AVG", "OBP"])

In [7]:
gc_stats

,Number,Last,First,GP,AVG,OBP
0,00,H,Cameron,23,.200,.535
1,1,H,Addison,22,.179,.303
2,3,T,Kyndall,23,.237,.370
3,4,O,Mia,18,.308,.357
4,7,M,Camilla,11,.188,.435
5,9,V,Lauren,23,.244,.279
6,11,M,Addison,6,.000,.833
7,11,J,Syndi,3,.000,.000
8,13,W,Kyler,23,.300,.364
9,15,K,Brooklyn,4,.000,.286
10,16,C,Lyric,7,.500,.615
11,33,NaN,AC,23,.459,.583
12,44,R,Taylor,23,.206,.341
13,98,S,Ava,20,.194,.306
14,Totals,NaN,NaN,23,.258,.406
15,NaN,NaN,NaN,NaN,NaN,NaN
16,Glossary,NaN,NaN,GP=Games played,AVG=Batting average,OBP=On-base percentage